# Generated by Django 5.2.17 on 2026-09-23 12:07

import affiliates.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Affiliate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=affiliates.models._code,
                        editable=False,
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "payout_method",
                    models.CharField(
                        choices=[("mpesa", "M-Pesa"), ("bank", "Bank transfer")],
                        default="mpesa",
                        max_length=10,
                    ),
                ),
                (
                    "mpesa_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="M-Pesa number"
                    ),
                ),
                (
                    "mpesa_name",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        verbose_name="Name registered on M-Pesa",
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=80)),
                ("bank_account_name", models.CharField(blank=True, max_length=80)),
                ("bank_account_number", models.CharField(blank=True, max_length=40)),
                ("bank_branch", models.CharField(blank=True, max_length=80)),
                ("notes", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Signed up"),
                            ("qualified", "Qualified (unpaid)"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=20, max_digits=8),
                ),
                ("signup_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("flagged", models.BooleanField(default=False)),
                ("flag_reason", models.CharField(blank=True, max_length=200)),
                ("qualified_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "paid_ref",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Payment reference"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="affiliates.affiliate",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
