# Generated by Django 5.2.17 on 2026-09-23 12:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Main branch", max_length=40, verbose_name="Branch name"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Location"
                    ),
                ),
                ("is_main", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "pos_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="POS expires"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "branches",
                "ordering": ["-is_main", "name"],
                "unique_together": {("vendor", "name")},
            },
        ),
        migrations.CreateModel(
            name="InsightQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.CharField(max_length=600)),
                ("answer", models.TextField()),
                ("engine", models.CharField(default="rules", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight_questions",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InsightReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("days", models.PositiveSmallIntegerField(default=30)),
                ("report", models.JSONField()),
                ("snapshot", models.JSONField(default=dict)),
                ("engine", models.CharField(default="rules", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Blank means the whole business",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight_reports",
                        to="pos.branch",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight_reports",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("pos", "Walk-in"), ("booking", "Booking")],
                        db_index=True,
                        default="pos",
                        max_length=10,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=80, verbose_name="Client"),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("number", models.PositiveIntegerField(default=0)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=10,
                        verbose_name="Receipt no.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "In service"),
                            ("done", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "gross",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_type",
                    models.CharField(
                        blank=True,
                        choices=[("percent", "%"), ("amount", "KES")],
                        max_length=8,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "Cash"),
                            ("mpesa", "M-Pesa"),
                            ("card", "Card"),
                            ("split", "M-Pesa & cash"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "payment_ref",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Transaction ref"
                    ),
                ),
                (
                    "payer_name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Paid by (name)"
                    ),
                ),
                (
                    "amount_tendered",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "paid_mpesa",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "paid_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("reconcile_note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("placed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="pos.branch",
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who rang up the sale",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("staff", "Staff"), ("cashier", "Cashier")],
                        default="staff",
                        max_length=10,
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Senior stylist", "Nail tech"',
                        max_length=60,
                        verbose_name="Job title",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="ID number"
                    ),
                ),
                (
                    "hired_on",
                    models.DateField(blank=True, null=True, verbose_name="Start date"),
                ),
                ("photo", models.ImageField(blank=True, upload_to="staff/")),
                (
                    "bio",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Short bio"
                    ),
                ),
                (
                    "payout_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="M-Pesa number for pay"
                    ),
                ),
                (
                    "commission_type",
                    models.CharField(
                        choices=[
                            ("percent", "Percentage of the service"),
                            ("fixed", "Fixed amount per service"),
                        ],
                        default="percent",
                        max_length=8,
                        verbose_name="Commission",
                    ),
                ),
                (
                    "commission_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percent (e.g. 30) or KES per service (e.g. 200)",
                        max_digits=10,
                        verbose_name="Rate",
                    ),
                ),
                (
                    "show_on_site",
                    models.BooleanField(
                        default=True, verbose_name="Show on the public page"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff",
                        to="pos.branch",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "staff",
                "ordering": ["user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Client name")),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "duration_min",
                    models.PositiveSmallIntegerField(
                        default=60, verbose_name="Minutes"
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("phone", "Phone / WhatsApp"),
                            ("walk_in", "Walk-in"),
                        ],
                        default="online",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("confirmed", "Confirmed"),
                            ("done", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No-show"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="vendors.menuitem",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="vendors.vendor",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="pos.branch",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking",
                        to="pos.order",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for anyone available",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to="pos.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "time"],
            },
        ),
        migrations.CreateModel(
            name="StaffPayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField(default=0)),
                ("period_from", models.DateField(blank=True, null=True)),
                ("period_to", models.DateField(blank=True, null=True)),
                ("services_count", models.PositiveIntegerField(default=0)),
                (
                    "sales_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Bonus / tips",
                    ),
                ),
                (
                    "deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Deductions / advances",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Paid"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("mpesa", "M-Pesa"),
                            ("cash", "Cash"),
                            ("bank", "Bank transfer"),
                        ],
                        default="mpesa",
                        max_length=10,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="M-Pesa / bank ref"
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("paid_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="pos.staff",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "list_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("unit_net", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("qty", models.PositiveIntegerField(default=1)),
                (
                    "line_net",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "line_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "line_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sold",
                        to="vendors.menuitem",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pos.order",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lines",
                        to="pos.staff",
                    ),
                ),
                (
                    "payout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lines",
                        to="pos.staffpayout",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StaffService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "commission_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("percent", "Percentage of the service"),
                            ("fixed", "Fixed amount per service"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "commission_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_links",
                        to="vendors.menuitem",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_links",
                        to="pos.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["service__name"],
            },
        ),
        migrations.AddField(
            model_name="staff",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                related_name="staff",
                through="pos.StaffService",
                to="vendors.menuitem",
            ),
        ),
        migrations.CreateModel(
            name="StaffShift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("starts", models.TimeField()),
                ("ends", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("worked", "Worked"),
                            ("absent", "Absent"),
                            ("leave", "On leave"),
                        ],
                        default="planned",
                        max_length=8,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_shifts",
                        to="pos.branch",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="pos.staff",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_shifts",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "starts"],
            },
        ),
        migrations.CreateModel(
            name="BranchPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "net_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Entered the same way as the service: VAT included, or net if the service adds VAT.",
                        max_digits=10,
                        verbose_name="Price (KES)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Public price (KES)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="pos.branch",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_prices",
                        to="vendors.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["item__name"],
                "unique_together": {("branch", "item")},
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("products", "Products & supplies"),
                            ("rent", "Rent"),
                            ("salaries", "Salaries & wages"),
                            ("utilities", "Utilities (power, water)"),
                            ("transport", "Transport"),
                            ("marketing", "Marketing"),
                            ("equipment", "Equipment & repairs"),
                            ("licences", "Licences & fees"),
                            ("other", "Other"),
                        ],
                        default="products",
                        max_length=12,
                    ),
                ),
                ("description", models.CharField(max_length=160)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "paid_via",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("mpesa", "M-Pesa"),
                            ("card", "Card"),
                            ("split", "M-Pesa & cash"),
                        ],
                        default="cash",
                        max_length=10,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Receipt / M-Pesa ref"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="pos.branch",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["vendor", "date"], name="pos_expense_vendor__fdf850_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["vendor", "status"], name="pos_order_vendor__fd7272_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["vendor", "paid_at"], name="pos_order_vendor__85917d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["vendor", "date"], name="pos_booking_vendor__a955c0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="staffservice",
            unique_together={("staff", "service")},
        ),
        migrations.AddIndex(
            model_name="staffshift",
            index=models.Index(
                fields=["vendor", "date"], name="pos_staffsh_vendor__3316a8_idx"
            ),
        ),
    ]
