# Generated by Django 5.2.17 on 2026-09-23 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


def copy_service_to_items(apps, schema_editor):
    """Each existing booking's single service becomes its first booking line."""
    Booking = apps.get_model("pos", "Booking")
    BookingItem = apps.get_model("pos", "BookingItem")
    for b in Booking.objects.filter(service__isnull=False).select_related("service"):
        BookingItem.objects.create(booking=b, service=b.service, name=b.service.name, price=b.service.price,
                                   duration_min=b.service.duration_min or 0, position=0)


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0001_initial"),
        ("vendors", "0002_seed_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="show_on_site",
        ),
        migrations.CreateModel(
            name="BookingItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("duration_min", models.PositiveSmallIntegerField(default=0)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pos.booking",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_items",
                        to="vendors.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.RunPython(copy_service_to_items, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="booking",
            name="service",
        ),
    ]
