# Generated by Django 5.2.17 on 2026-09-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0002_booking_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="national_id",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="payout_phone",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="photo",
        ),
    ]
