# Generated by Django 5.2.17 on 2026-09-23 12:07

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "service categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "premium_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=1000,
                        max_digits=10,
                        verbose_name="Premium fee (KES, per month)",
                    ),
                ),
                (
                    "pos_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=1500,
                        max_digits=10,
                        verbose_name="POS module fee (KES, per month)",
                    ),
                ),
                (
                    "affiliate_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=10,
                        verbose_name="Affiliate reward per qualified sign-up (KES)",
                    ),
                ),
                (
                    "free_menu_limit",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Free plan: max services"
                    ),
                ),
                (
                    "free_photo_limit",
                    models.PositiveIntegerField(
                        default=3, verbose_name="Free plan: max gallery photos"
                    ),
                ),
                (
                    "payment_instructions",
                    models.TextField(
                        default="Pay by card or M-Pesa through Paystack. Your plan is switched on (or extended by a month) as soon as the payment clears."
                    ),
                ),
                (
                    "branches_open",
                    models.BooleanField(
                        default=False,
                        help_text="Off: only vendors already switched on can use multiple branches.",
                        verbose_name="Branches open to all vendors",
                    ),
                ),
                (
                    "support_whatsapp",
                    models.CharField(default="254717183416", max_length=20),
                ),
                (
                    "support_email",
                    models.EmailField(default="beauty@isoftke.com", max_length=254),
                ),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("dish", "Service"),
                            ("cuisine", "Speciality"),
                            ("meal", "Occasion"),
                            ("menu", "Service type"),
                        ],
                        default="dish",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional intro shown on the tag page"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("county", "County"), ("area", "Town / area")],
                        max_length=10,
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="Optional unique intro for this location page",
                    ),
                ),
                (
                    "county",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="vendors.location",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("brand_name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                (
                    "menu_token",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=24,
                        unique=True,
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("salon", "Salon"),
                            ("spa", "Spa"),
                            ("barber", "Barber"),
                            ("nails", "Nail studio"),
                            ("makeup", "Makeup artist"),
                            ("massage", "Massage"),
                            ("beauty_shop", "Beauty shop"),
                            ("wellness", "Wellness"),
                        ],
                        default="salon",
                        max_length=12,
                    ),
                ),
                ("logo", models.ImageField(blank=True, upload_to="logos/")),
                ("cover", models.ImageField(blank=True, upload_to="covers/")),
                ("tagline", models.CharField(blank=True, max_length=160)),
                ("about", django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="WhatsApp number (e.g. 2547XXXXXXXX)",
                    ),
                ),
                (
                    "county",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Baringo", "Baringo"),
                            ("Bomet", "Bomet"),
                            ("Bungoma", "Bungoma"),
                            ("Busia", "Busia"),
                            ("Elgeyo-Marakwet", "Elgeyo-Marakwet"),
                            ("Embu", "Embu"),
                            ("Garissa", "Garissa"),
                            ("Homa Bay", "Homa Bay"),
                            ("Isiolo", "Isiolo"),
                            ("Kajiado", "Kajiado"),
                            ("Kakamega", "Kakamega"),
                            ("Kericho", "Kericho"),
                            ("Kiambu", "Kiambu"),
                            ("Kilifi", "Kilifi"),
                            ("Kirinyaga", "Kirinyaga"),
                            ("Kisii", "Kisii"),
                            ("Kisumu", "Kisumu"),
                            ("Kitui", "Kitui"),
                            ("Kwale", "Kwale"),
                            ("Laikipia", "Laikipia"),
                            ("Lamu", "Lamu"),
                            ("Machakos", "Machakos"),
                            ("Makueni", "Makueni"),
                            ("Mandera", "Mandera"),
                            ("Marsabit", "Marsabit"),
                            ("Meru", "Meru"),
                            ("Migori", "Migori"),
                            ("Mombasa", "Mombasa"),
                            ("Murang'a", "Murang'a"),
                            ("Nairobi", "Nairobi"),
                            ("Nakuru", "Nakuru"),
                            ("Nandi", "Nandi"),
                            ("Narok", "Narok"),
                            ("Nyamira", "Nyamira"),
                            ("Nyandarua", "Nyandarua"),
                            ("Nyeri", "Nyeri"),
                            ("Samburu", "Samburu"),
                            ("Siaya", "Siaya"),
                            ("Taita-Taveta", "Taita-Taveta"),
                            ("Tana River", "Tana River"),
                            ("Tharaka-Nithi", "Tharaka-Nithi"),
                            ("Trans Nzoia", "Trans Nzoia"),
                            ("Turkana", "Turkana"),
                            ("Uasin Gishu", "Uasin Gishu"),
                            ("Vihiga", "Vihiga"),
                            ("Wajir", "Wajir"),
                            ("West Pokot", "West Pokot"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "town",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Town / area"
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=200)),
                (
                    "map_link",
                    models.URLField(blank=True, verbose_name="Google Maps link"),
                ),
                (
                    "branches_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Turn on to run more than one outlet under this account.",
                        verbose_name="Multiple branches",
                    ),
                ),
                (
                    "accepts_bookings",
                    models.BooleanField(
                        default=True, verbose_name="Take online bookings"
                    ),
                ),
                (
                    "home_service",
                    models.BooleanField(
                        default=False, verbose_name="Offers home / mobile service"
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[("free", "Free"), ("premium", "Premium")],
                        default="free",
                        max_length=10,
                    ),
                ),
                (
                    "premium_paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last premium payment"
                    ),
                ),
                (
                    "premium_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Premium expires"
                    ),
                ),
                (
                    "pos_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="POS module expires"
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="Approved by admin"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "area_loc",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="area_vendors",
                        to="vendors.location",
                    ),
                ),
                (
                    "county_loc",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="county_vendors",
                        to="vendors.location",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vendors",
                        to="vendors.tag",
                        verbose_name="Services & specialities",
                    ),
                ),
            ],
            options={
                "ordering": ["-plan", "brand_name"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/")),
                ("caption", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("details", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="offers/")),
                ("starts", models.DateField(blank=True, null=True)),
                ("ends", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("image", models.ImageField(blank=True, upload_to="services/")),
                (
                    "net_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The price you enter. Choose below whether VAT is already included.",
                        max_digits=10,
                        null=True,
                        verbose_name="Price (KES)",
                    ),
                ),
                (
                    "vat_mode",
                    models.CharField(
                        choices=[
                            ("incl", "Price includes VAT"),
                            ("add", "Add 16% VAT on top"),
                        ],
                        default="incl",
                        max_length=4,
                        verbose_name="VAT",
                    ),
                ),
                (
                    "duration_min",
                    models.PositiveSmallIntegerField(
                        default=60, verbose_name="Duration (minutes)"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No discount"),
                            ("percent", "Percent off"),
                            ("amount", "KES off"),
                        ],
                        max_length=8,
                        verbose_name="Discount",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percent off (e.g. 20) or KES off (e.g. 500)",
                        max_digits=10,
                        verbose_name="Discount amount",
                    ),
                ),
                (
                    "discount_ends",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank to keep it running",
                        null=True,
                        verbose_name="Discount ends",
                    ),
                ),
                (
                    "price_on_request",
                    models.BooleanField(
                        default=False,
                        help_text="No fixed price — clients ask for a quote (bridal, events, home visits).",
                        verbose_name="Price on request",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=10,
                        verbose_name="Public price (KES)",
                    ),
                ),
                ("description", django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="vendors.menucategory",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["category__order", "name"],
            },
        ),
        migrations.AddField(
            model_name="menucategory",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="vendors.vendor",
            ),
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("inquiry", "Question"), ("quote", "Quote request")],
                        default="inquiry",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("phone", models.CharField(max_length=20)),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("converted", "Booked"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vendors.menuitem",
                        verbose_name="Service",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("name", models.CharField(blank=True, max_length=80)),
                ("orders_count", models.PositiveIntegerField(default=0)),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("opt_out", models.BooleanField(default=False)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "stars",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 star"),
                            (2, "2 stars"),
                            (3, "3 stars"),
                            (4, "4 stars"),
                            (5, "5 stars"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("is_approved", models.BooleanField(default=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(blank=True, max_length=6)),
                ("code_expires", models.DateTimeField(blank=True, null=True)),
                ("code_attempts", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("vendor", "email")},
            },
        ),
        migrations.CreateModel(
            name="OpeningHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("opens", models.TimeField(blank=True, null=True)),
                ("closes", models.TimeField(blank=True, null=True)),
                ("closed", models.BooleanField(default=False)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hours",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "opening hours",
                "ordering": ["day"],
                "unique_together": {("vendor", "day")},
            },
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["vendor", "is_available"], name="menuitem_vendor_avail_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="menucategory",
            unique_together={("vendor", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("vendor", "phone")},
        ),
    ]
