# Generated by Django 5.2.17 on 2026-09-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0002_seed_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="menu_token",
        ),
    ]
