# Generated by Django 5.2.17 on 2026-09-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0004_discounts_in_kes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Discount (KES off)",
            ),
        ),
    ]
